name: CD

on:
  push:
    branches:
      - dev

jobs:    
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: flipday/frontend

  update-docker:
    runs-on: ubuntu-latest
    needs: build-docker

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2 
      
      - name: SSH command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: | 
            docker stop flipday-front
            docker rm flipday-front
            docker rmi flipday/frontend
            docker run -d -p 80:80 --name flipday-front flipday/frontend
    